# Changes here will be overwritten by Copier
_commit: v0.1.3
_src_path: https://code.siemens.com/learning-systems/copier/maven-single.git
artifact_id: maven_action
assembly_format:
- dir
- zip
group_id: io.github.dbogdoll
kotlin_apiVersion: '1.9'
kotlin_jvm_target: '17'
kotlin_languageVersion: '1.9'
kotlin_version: 1.9.24
use_assembly: true
use_cicd: false
use_clickt: true
